/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package roombaif;

/**
 *
 * @author phillips
 */
public class DummyInputFrame extends javax.swing.JFrame {

    private RoombaDummyIF roombaDummyIF;

    /**
     * Creates new form DummyInputFrame
     */
    public DummyInputFrame() {
        initComponents();
    }

    /**
     * Creates new form DummyInputFrame for the roombaDummyIF
     */
    public DummyInputFrame(RoombaDummyIF roombaDummyIF) {
        initComponents();

        this.roombaDummyIF = roombaDummyIF;
        SensorPacket[] sensorPacketsRequested = roombaDummyIF.getSensorPacketsRequested();

        String descriptions = "";
        String zeros = "";
        int i;
        for (i = 0; i < sensorPacketsRequested.length - 1; i++) {
            descriptions = descriptions.concat(sensorPacketsRequested[i].description()).concat(", ");
            zeros = zeros.concat("0, ");
        }
        descriptions = descriptions.concat(sensorPacketsRequested[i].description());
        zeros = zeros.concat("0");
        requestedPacketsTextArea.setText(descriptions);
        sensorValuesTextArea.setText(zeros);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        sendButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        sensorValuesTextArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        requestedPacketsTextArea = new javax.swing.JTextArea();
        sentOKLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Enter new values for the sensor data as integers seprated by commas and press Send.");

        sendButton.setText("Send");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        sensorValuesTextArea.setColumns(20);
        sensorValuesTextArea.setRows(5);
        jScrollPane1.setViewportView(sensorValuesTextArea);

        requestedPacketsTextArea.setEditable(false);
        requestedPacketsTextArea.setColumns(20);
        requestedPacketsTextArea.setLineWrap(true);
        requestedPacketsTextArea.setRows(5);
        jScrollPane2.setViewportView(requestedPacketsTextArea);

        sentOKLabel.setText("status...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sentOKLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sendButton))
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sendButton)
                    .addComponent(sentOKLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        // TODO add your handling code here:
        String[] values = sensorValuesTextArea.getText().split(",");
        if (values.length > roombaDummyIF.sensorPacketsRequested.length) {
            sentOKLabel.setText("too many values entered");
        } else if (values.length < roombaDummyIF.sensorPacketsRequested.length) {
            sentOKLabel.setText("too few values entered");
        }
        int[] temp = new int[values.length];
        boolean goodString = true;
        for (int i = 0; i < values.length; i++) {
            try {
                temp[i] = Integer.parseInt(values[i].trim());
            } catch (NumberFormatException ex) {
                sentOKLabel.setText("bad format around value[" + i + "]: " + values[i]);
                goodString = false;
                break;
            }
        }
        if (goodString) {
            roombaDummyIF.setSensorData(temp);
            sentOKLabel.setText("OK");
        }
    }//GEN-LAST:event_sendButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DummyInputFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DummyInputFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DummyInputFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DummyInputFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DummyInputFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea requestedPacketsTextArea;
    private javax.swing.JButton sendButton;
    private javax.swing.JTextArea sensorValuesTextArea;
    private javax.swing.JLabel sentOKLabel;
    // End of variables declaration//GEN-END:variables
}
